name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run test-ci
    - name: Report coverage
      uses: slavcodev/coverage-monitor-action@1.2.0
      with:
        # The GITHUB_TOKEN secret.
        github_token:  ${{ secrets.GITHUB_TOKEN }}
        clover_file: ./coverage/clover.xml
        check: false
    - name: Build static files
      run: npm run build      
